DROP TABLE IF EXISTS bonos CASCADE;
DROP TABLE IF EXISTS clases CASCADE;
DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS teacher CASCADE;
DROP TABLE IF EXISTS test CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;